properties([disableConcurrentBuilds()])

pipeline {
    agent {
         label 'Test'    
         }
             
    triggers { pollSCM('* * * * *') }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    stages {
       
        steps("create docker image for test") {
            steps {
                echo " ============== start building image for deploy  =================="
                dir ('ASP.NET-15/Shop-15') {
                sh ' sudo docker build  -t nazarserver/shoptest .'
                sh 'sudo docker run -d --restart=always -p 80:80  nazarserver/shoptest'    
            }
            }
        stage("create docker image")
            agent { 
                label 'ubuntu'
            }
            steps{
                echo "================ Start building images for integration========="
                dir ('ASP.NET-15/Shop-15') {
                sh ' sudo docker build  -t nazarserver/shop .'
                sh 'sudo docker run -d --restart=always -p 80:80  nazarserver/shop'
            }
        }
       
    }
 }   
}
