pipeline {
	agent any
	environment {
      workspace         = "home/ubuntu/ansible"   
	}
       parameters {
  choice choices: ['a1', 'a2'], name: 'Choice-Diawi'

}
    stages {
     	stage("Build"){
			steps{
				dir("${workspace}"){
					sh 'ansible-playbook -i  $Choice-Diawi  play1.yml'
				}
			}
		}
    }
